### ISSUE TITLE
Multi-record requests (at least with CSV) don't work

### ISSUE THREAD

**Issue by andremoeller** [aws/sagemaker-tensorflow-training-toolkit#174]
Inspired by: https://github.com/aws/sagemaker-python-sdk/issues/672

This code just takes the first row of CSV:
https://github.com/aws/sagemaker-tensorflow-container/blob/master/src/tf_container/serve.py#L196-L213

There's a todo there to fix this in the code:

`# TODO csv is constructed as 2D arrays always, overall multi-point calls must be fixed`

**Comment by nadiaya** [comment]
Thank you! Added to our backlog.

**Comment by laurenyu** [comment]
closing, as this was for the legacy TensorFlow images. the current TensorFlow Serving image code is at https://github.com/aws/sagemaker-tensorflow-serving-container
