### ISSUE TITLE
Multiple inputs failing with different types

### ISSUE THREAD

**Issue by mhwilder** [aws/sagemaker-tensorflow-training-toolkit#188]
I've been working to deploy a TensorFlow model in SageMaker that takes 3 inputs (2 images and one float array). I'm passing the images in as base64 encoded strings and the float just in a numpy array. I've tested under a couple of different conditions and I'm pretty sure I've isolated the problem to the ```_value_to_tensor()``` function in [proxy_client.py](https://github.com/aws/sagemaker-tensorflow-container/blob/master/src/tf_container/proxy_client.py).
```
def _value_to_tensor(self, value):
    """Converts the given value to a tensor_pb2.TensorProto. Used on code path for creating PredictRequests."""
    if isinstance(value, tensor_pb2.TensorProto):
        return value

    msg = """Unable to convert value to TensorProto: {}. 
    Valid formats: tensor_pb2.TensorProto, list, numpy.ndarray"""
    try:
        # TODO: tensorflow container supports prediction requests with ONLY one tensor as input
        input_type = self.input_type_map.values()[0]
        ndarray = np.asarray(value)
        return make_tensor_proto(values=ndarray, dtype=input_type, shape=ndarray.shape)
    except Exception:
        raise ValueError(msg.format(value))
```

The code in this function is pretty suspicious with the "TODO" note and the logic in the following line that just chooses the first type:
```
input_type = self.input_type_map.values()[0]
```
This is clearly going to cause problems with models that accept inputs with different types. As a side note, this code will also fail in Python 3 with the error "TypeError: 'dict_values' object does not support indexing" which will be relevant when you upgrade the containers to Py3.

I don't have a simple example to reproduce this, but I can give a bit of background on what I was experiencing. I made the model simpler to just accept just one image (and hard coded the other inputs within the model) and it worked just fine. Then I added the float input back to the model (so there was one image and one float array). When I did this, it failed (see error below). After investigating more, I changed the second input to be the other image (and made the float input hard coded again). This model worked just fine suggesting that the code runs fine with multiple inputs as long as they are all the same type.

Here are the CloudWatch errors I observed:

```
[2019-05-07 15:55:46,460] ERROR in serving: Unable to convert value to TensorProto: [u'b64_image_string'].
Valid formats: tensor_pb2.TensorProto, list, numpy.ndarray
```
```
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/container_support/serving.py", line 228, in _invoke
self.transformer.transform(content, input_content_type, requested_output_content_type)
File "/usr/local/lib/python2.7/dist-packages/tf_container/serve.py", line 296, in transform
return self.transform_fn(data, content_type, accepts), accepts
File "/usr/local/lib/python2.7/dist-packages/tf_container/serve.py", line 224, in f
prediction = self.predict_fn(input)
File "/usr/local/lib/python2.7/dist-packages/tf_container/serve.py", line 239, in predict_fn
return self.proxy_client.request(data)
File "/usr/local/lib/python2.7/dist-packages/tf_container/proxy_client.py", line 83, in request
return request_fn(data)
File "/usr/local/lib/python2.7/dist-packages/tf_container/proxy_client.py", line 114, in predict
request = self._create_predict_request(data)
File "/usr/local/lib/python2.7/dist-packages/tf_container/proxy_client.py", line 129, in _create_predict_request
input_map = self._create_input_map(data)
File "/usr/local/lib/python2.7/dist-packages/tf_container/proxy_client.py", line 219, in _create_input_map
return {k: self._value_to_tensor(v) for k, v in data.items()}
File "/usr/local/lib/python2.7/dist-packages/tf_container/proxy_client.py", line 219, in <dictcomp>
return {k: self._value_to_tensor(v) for k, v in data.items()}
File "/usr/local/lib/python2.7/dist-packages/tf_container/proxy_client.py", line 237, in _value_to_tensor
raise ValueError(msg.format(value))
```

**Comment by mhwilder** [comment]
As a side note: I was able to get around this issue by implementing the base64 conversions in the input_fn instead of handling it in the serving_input_receiver_fn. It still seems that this could be an issue in certain cases.

**Comment by ChoiByungWook** [comment]
Hello @mhwilder,

Apologies for the late response and thank you for bringing this issue to our attention.

It is unfortunate that the serving support in this code base is causing problems and isn't sufficient enough for use cases above single tensor inputs.

For now, I'll add this to our backlog and hopefully I can discuss with the team on how to support this.

In the meanwhile, please see if the REST API TensorFlow serving container suffices. For instructions on how to use the Rest API TFS container:  https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/tensorflow/deploying_tensorflow_serving.rst

If you would like to see the implementations of that container please see: https://github.com/aws/sagemaker-tensorflow-serving-container

We also welcome and appreciate modifications and contributions from anyone, so feel free to submit a PR.

Thanks!

**Comment by laurenyu** [comment]
closing, as we no longer release new versions of the legacy TensorFlow images. For the current TensorFlow Serving images, see https://github.com/aws/sagemaker-tensorflow-serving-container
