### ISSUE TITLE
Where are the container images for script mode ?

### ISSUE THREAD

**Issue by keerath** [aws/sagemaker-tensorflow-training-toolkit#202]
I check the script-mode branch too, on running "python setup.py sdist" it produces a tar file with version 0.1.1.dev0 as the VERSION file has this string. But framework_support_installable=sagemaker_tensorflow_container-2.0.0.tar.gz in the Docker file. 
I don't see any Dockerfiles related to script mode with py3 on the master branch. Is it safe to assume that the script-mode is stable and if so, why are there so many inconsistencies with it ?

**Comment by ChoiByungWook** [comment]
Hello @keerath,

Thank you for bringing this to our attention.

It seems that this is an error on our part and we are looking into fixing this issue.

**Comment by keerath** [comment]
@ChoiByungWook @icywang86rui In the meanwhile, could you please let me know if the script-mode branch is stable because after changing the version file I was able to build the images.

**Comment by ChoiByungWook** [comment]
@keerath,

Yes this repo should stable minus the version hiccup.

**Comment by keerath** [comment]
@ChoiByungWook Thanks a lot for the confirmation, also I was able to upload these images to ECR and run integration tests successfully.

**Comment by leolorenzoluis** [comment]
@ChoiByungWook Do we need to build our own images? Is there any AWS public repo that can pull the script mode containers easily? I want to use the sagemaker python sdk with Estimator rather than using boto

**Comment by keerath** [comment]
@leolorenzoluis I was also under the impression that we had to build these images ourselves and upload them to ECR, but you don't have to do that. Please look at the link below of how to reference these images.

https://docs.aws.amazon.com/sagemaker/latest/dg/pre-built-containers-frameworks-deep-learning.html
