### ISSUE TITLE
docker/1.14.0/py3/Dockfile.cpu can't be build through.

### ISSUE THREAD

**Issue by Seninus** [aws/sagemaker-tensorflow-training-toolkit#248]
i see the base Dockfile and final Dockfile are combined  into one Dockfile. 
meanwhile 
1. the readme.rst is not updated yet. 
2. this one Dockfile can't really be built through.

**Comment by ajaykarpur** [comment]
Hi @Seninus, thanks for bringing this to our attention. Can you please provide more details about the issue (including any relevant error messages) and instructions to reproduce it?

**Comment by Seninus** [comment]
COPY failed: stat /var/lib/docker/tmp/docker-builder302350409/sagemaker_tensorflow_container-2.0.0.tar.gz: no such file or directory
---  
Curious what is sagemaker_tensorflow_container-2.0.0.tar.gz ?  i don't see anywhere creating this tar.gz file and in the Dockfile, the copy action failed.

**Comment by surajkota** [comment]
Hi @Seninus please change [line 77](https://github.com/aws/sagemaker-tensorflow-container/blob/master/docker/1.14.0/py3/Dockerfile.cpu#L77) in Dockerfile to - 

`
ARG framework_support_installable=sagemaker_tensorflow_container-*.tar.gz`

Use the following commands to build the image - 
```
cd sagemaker-tensorflow-container
python setup.py sdist
cp dist/sagemaker_tensorflow_container-*.tar.gz docker/1.14.0/py3
cd docker/1.14.0/py3/
docker build -t <image_name>:<tag> -f Dockerfile.cpu .
```

We will update the readme. Let us know if you have any more issues

**Comment by ChaiBapchya** [comment]
@surajkota can you take a look at the readme? Updated it.
@ajaykarpur @Seninus
