### ISSUE TITLE
Custom CUDA Operations

### ISSUE THREAD

**Issue by JKurzer** [aws/sagemaker-tensorflow-training-toolkit#260]
What's the best way to integrate support for new or novel cuda operations such as ROI Pooling? Did I miss an obvious approach?

If it's not currently a feature, would you accept a patch to factor in better support?

**Comment by nadiaya** [comment]
We do accept patches.

Also you could use your own base image and just install sagemaker-tensorflow-container library in there to get the same user experience when running on SageMaker:
https://github.com/aws/sagemaker-tensorflow-container/blob/master/docker/1.14.0/py3/Dockerfile.cpu#L110
https://github.com/aws/sagemaker-tensorflow-container/blob/master/docker/1.14.0/py3/Dockerfile.cpu#L128

**Comment by laurenyu** [comment]
The Dockerfiles have now been moved to https://github.com/aws/deep-learning-containers
