### ISSUE TITLE
Incorrect usage: pytest tests/functional

### ISSUE THREAD

**Issue by ChaiBapchya** [aws/sagemaker-tensorflow-training-toolkit#378]
https://github.com/aws/sagemaker-tensorflow-container/tree/script-mode#functional-tests

mentions Functional tests as a way of running tests on Sagemaker

```
pytest test/functional --aws-id <your_aws_id> \
                       --docker-base-name <your_docker_image> \
                       --instance-type <amazon_sagemaker_instance_type> \
                       --tag <your_docker_image_tag
```
However, there is no folder by the name "functional"

**Comment by ChuyangDeng** [comment]
Hi @ChaiBapchya "functional" tests are removed from current branch as well as tf-2.

You can find the functional tests in old containers in branch "r1.0": https://github.com/aws/sagemaker-tensorflow-container/tree/r1.0/test/functional

With that being said, we will update the README to avoid confusions

**Comment by laurenyu** [comment]
looks like this was taken care of in #380 and #381
