### ISSUE TITLE
Parameter Server entrypoint

### ISSUE THREAD

**Issue by ChaiBapchya** [aws/sagemaker-tensorflow-training-toolkit#386]
Why doesn't entry-point get called for parameter server? Why is it only for non PS distributed training?

https://github.com/aws/sagemaker-tensorflow-training-toolkit/blob/60d8c10bb5214e24ca3a5084bca8159b95810468/src/sagemaker_tensorflow_container/training.py#L157

**Comment by ChuyangDeng** [comment]
Hi @ChaiBapchya,

for this case, entry_point.run is called here: https://github.com/aws/sagemaker-tensorflow-training-toolkit/blob/60d8c10bb5214e24ca3a5084bca8159b95810468/src/sagemaker_tensorflow_container/training.py#L143
then:
https://github.com/aws/sagemaker-tensorflow-training-toolkit/blob/60d8c10bb5214e24ca3a5084bca8159b95810468/src/sagemaker_tensorflow_container/training.py#L112

and in this case, process runner is used: https://github.com/aws/sagemaker-training-toolkit/blob/master/src/sagemaker_training/entry_point.py#L34
