### ISSUE TITLE
local-gpu for TF horovod local sagemaker integration test?

### ISSUE THREAD

**Issue by ChaiBapchya** [aws/sagemaker-tensorflow-training-toolkit#388]
https://github.com/aws/sagemaker-python-sdk/blob/69d06ad9bba0f108df0f2a589831f254db0997a8/tests/integ/test_horovod.py#L58

Why does this test for `local` instead of `local-gpu`?
Wouldn't this test for CPU only? For testing with nvidia-docker for cuda version of the framework, shouldn't local-gpu be used?

@ChuyangDeng

**Comment by laurenyu** [comment]
Transferring the issue to a more appropriate repository - the Python SDK tests are not intended to test the images - just the Python SDK.

The corresponding test in this repo does skip GPU entirely: https://github.com/aws/sagemaker-tensorflow-training-toolkit/blob/master/test/integration/local/test_horovod.py#L25. However, we could potentially modify it to run for the 1 instance + 2 processes case.

**Comment by laurenyu** [comment]
added in #389 and #390.
